version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_service
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data

volumes:
  redisinsight_data:
